Authorization/AspNetSecurity-m4/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetSecurity_m4.Controllers
{
    public class AccountController: Controller
    {
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

Authorization/AspNetSecurity-m4/Controllers/ConferenceController.cs
using System.Threading.Tasks;
using AspNetSecurity_m4.Api;
using AspNetSecurity_m4_Shared.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetSecurity_m4.Controllers
{
    [Authorize]
    public class ConferenceController: Controller
    {
        private readonly ConferenceApiService service;

        public ConferenceController(ConferenceApiService service)
        {
            this.service = service;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "Organizer - Conference Overview";
            return View(await service.GetAll());
        }

        [Authorize(Policy = "OrganizerAccessPolicy")]
        public IActionResult Add()
        {
            ViewBag.Title = "Organizer - Add Conference";
            return View(new ConferenceModel());
        }

        [HttpPost]
        [Authorize(Policy = "OrganizerAccessPolicy")]
        public async Task<IActionResult> Add(ConferenceModel model)
        {
            if (ModelState.IsValid)
                await service.Add(model);

            return RedirectToAction("Index");
        }
    }
}

Authorization/AspNetSecurity-m4/Controllers/ProposalController.cs
using System.Threading.Tasks;
using AspNetSecurity_m4.Api;
using AspNetSecurity_m4_Shared.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetSecurity_m4.Controllers
{
    [Authorize]
    public class ProposalController: Controller
    {
        private readonly ConferenceApiService conferenceService;
        private readonly ProposalApiService proposalService;
        private readonly IAuthorizationService authorizationService;

        public ProposalController(ConferenceApiService conferenceService, ProposalApiService proposalService,
            IAuthorizationService authorizationService)
        {
            this.conferenceService = conferenceService;
            this.proposalService = proposalService;
            this.authorizationService = authorizationService;
        }

        public async Task<IActionResult> Index(int conferenceId)
        {
            var conference = await conferenceService.GetById(conferenceId);      
            ViewBag.Title = $"Speaker - Proposals For Conference {conference.Name} {conference.Location}";
            ViewBag.ConferenceId = conferenceId;

            return View(await proposalService.GetAllForConference(conferenceId));
        }

        [Authorize(Policy = "SpeakerAccessPolicy")]
        [Authorize(Policy = "YearsOfExperiencePolicy")]
        public IActionResult AddProposal(int conferenceId)
        {
            ViewBag.Title = "Speaker - Add Proposal";
            return View(new ProposalModel {ConferenceId = conferenceId});
        }

        [HttpPost]
        public async Task<IActionResult> AddProposal(ProposalModel proposal)
        {
            if (ModelState.IsValid)
                await proposalService.Add(proposal);
            return RedirectToAction("Index", new {conferenceId = proposal.ConferenceId});
        }

        public async Task<IActionResult> EditProposal(ProposalModel proposal)
        {
            var authResult = await authorizationService.AuthorizeAsync(User, proposal, "ProposalEditPolicy");
            if (authResult.Succeeded)
            {
                return View();
            }
            return RedirectToAction("AccessDenied", "Account");
        }

        [Authorize(Policy = "OrganizerAccessPolicy")]
        public async Task<IActionResult> Approve(int proposalId)
        {
            var proposal = await proposalService.Approve(proposalId);
            return RedirectToAction("Index", new { conferenceId = proposal.ConferenceId });
        }
    }
}

Authorization/AspNetSecurity-m4/Views/Conference/Add.cshtml
@using System.Threading.Tasks
@using AspNetSecurity_m4_Shared.Models
@model ConferenceModel
<form asp-action="Add">
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Name"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Name" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Location"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Location" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Start"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" type="date" asp-for="Start" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 col-md-offset-4">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

Authorization/AspNetSecurity-m4/Views/Conference/Index.cshtml
@using System.Threading.Tasks
@using AspNetSecurity_m4.Api
@using AspNetSecurity_m4_Shared.Models
@model IEnumerable<ConferenceModel>
@inject AttendeeApiService AttendeeService
<div class="row">
    <div class="col-md-10 col-md-offset-2">
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Start of event</th>
                <th>Attendees</th>
                <th>Actions</th>
            </tr>
            @foreach (var conference in Model)
            {
                <tr>
                    <td>@conference.Name</td>
                    <td>@conference.Location</td>
                    <td>@conference.Start.ToString("ddd d MMM")</td>
                    <td>@await AttendeeService.GetAttendeesTotal(conference.Id)</td>
                    <td>
                        <a asp-controller="Proposal" asp-action="Index" asp-route-conferenceId="@conference.Id">Proposals</a>
                    </td>
                </tr>
            }
        </table>
        <a asp-action="Add">Add</a>
        @foreach (var claim in User.Claims) {
            @claim.Type<br/>
            @claim.Value<br/>

        }
    </div>
</div>

Authorization/AspNetSecurity-m4/Views/Proposal/AddProposal.cshtml
@using System.Threading.Tasks
@using AspNetSecurity_m4_Shared.Models
@model ProposalModel
<form asp-action="AddProposal">
    <input type="hidden" asp-for="ConferenceId"/>

    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Title"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Title"/>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Speaker"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Speaker"/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 col-md-offset-4">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

Authorization/AspNetSecurity-m4/Views/Proposal/EditProposal.cshtml
Placeholder for edit form for proposal

Authorization/AspNetSecurity-m4/Views/Proposal/Index.cshtml
@using System.Threading.Tasks
@using AspNetSecurity_m4_Shared.Models
@using Microsoft.AspNetCore.Authorization

@model IEnumerable<ProposalModel>

@inject IAuthorizationService AuthorizationService

<div class="row">
    <div class="col-md-10 col-md-offset-2">
        <table class="table">
            <tr>
                <th>Title</th>
                <th>Speaker</th>
                <th>Approved</th>
                <th>Actions</th>
            </tr>
            @foreach (var proposal in Model)
            {
                <tr>
                    <td>@proposal.Title</td>
                    <td>@proposal.Speaker</td>
                    <td>
                        @if (proposal.Approved)
                        {
                            <div class="glyphicon glyphicon-check"></div>
                        }
                    </td>
                    <td>
                        @if (!proposal.Approved)
                        {
                            <a asp-action="Approve" asp-route-proposalId="@proposal.Id">Approve</a>
                        }
                    </td>
                </tr>
            }
        </table>
        
        @if ((await AuthorizationService.AuthorizeAsync(User, "SpeakerAccessPolicy")).Succeeded)
        {
            <a asp-action="AddProposal" asp-route-conferenceId="@ViewBag.ConferenceId">Add</a>
        }

    </div>
</div>

Authorization/AspNetSecurity-m4/Views/Shared/UnAuthorized.cshtml
You are not authorized to edit this document

Authorization/AspNetSecurity-m4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link href="~/site.css" rel="stylesheet" />
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <img src="~/img/ConfArchSmall.png" style="max-width:100%" />
        </div>
        <div class="col-md-9 titlecol">
            <span class="title">@ViewBag.Title</span>           
        </div>
    </div>
        <div>
            @RenderBody()
        </div>
    </div>
</body>
</html>